export interface Paciente {
    nome: string,
    genero: string,
    dataNascimento: string,
    CPF: string,
    rg: string,
    estadoCivil: string,
    telefone: string,
    email: string,
    naturalidade: string,
    contatoEmergencia: string,
    nomeEmergencia: string,
    alergias: string[],
    cuidadosEspecificos: string[],
    convenio: string,
    numConvenio: string,
    valConvenio: string,
    cep: number,
    cidade: string,
    estado: string,
    logradouro: string,
    numero: number,
    complemento: string,
    bairro: string,
    pontoReferencia: string,
}
